apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: xvdt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xvdt
    app.kubernetes.io/part-of: byoc-app-bclg
  name: xvdt
spec:
  rules:
  - host: xvdt-byoc-gdbc-tenant.apps.69ca897844fe5d1bc75d.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: xvdt
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
